### ISSUE TITLE
Coloring matched portion?

### ISSUE THREAD

**Issue by JoshCheek** [garybernhardt/selecta#67]
Favourite aspect of `ag` / `ack` is how they colour the matched portion. Thoughts on adding this to selecta?

![screenshot 2015-01-05 09 29 59](https://cloud.githubusercontent.com/assets/77495/5616007/940f937c-94bd-11e4-914e-2688af1fddad.png)

**Comment by garybernhardt** [comment]
I'm afraid of the color choice not working well on all color schemes (light background, dark background, weird stuff like solarized). We could just use ack's choice (red), which is probably reasonable. But then someone is going to want to change it, and I'm not willing to support custom color configuration, which leads me back to "I don't want to do this"...

**Comment by garybernhardt** [comment]
Some other changes on a branch made it easy to try this out, so I did: 
![screen shot 2015-01-14 at 2 02 26 pm](https://cloud.githubusercontent.com/assets/45707/5748605/0cbb26f8-9bf6-11e4-86f9-15e874073795.png)

I like it quite a bit. It certainly makes understanding the matching easier. Maybe I should get over the fear of colors not working. If it's good enough for ack, it's probably good enough for selecta. However, there may still be a nontrivial performance cost depending on what the algorithm ends up being, so we'll see.

**Comment by rschmitt** [comment]
For what it's worth, I implemented this a bit differently in Heatseeker:
![screen shot 2015-02-24 at 9 47 28 pm](https://cloud.githubusercontent.com/assets/3725049/6365588/c5d0e6e4-bc6e-11e4-8219-efd5c1c241fe.png)
I've come to prefer the picking out of individual characters, because it can actually serve to highlight the non-matching portions of the strings, making it easier to see how matches are different. Here's another example:
![screen shot 2015-02-24 at 9 49 06 pm](https://cloud.githubusercontent.com/assets/3725049/6365600/fc833de0-bc6e-11e4-8f40-853a4e5a5a04.png)

**Comment by garybernhardt** [comment]
I thought about doing that, but I'm almost positive that the allocations would kill performance. Welp!

**Comment by rschmitt** [comment]
I actually compute the scores a second time in order to render the matches. There's a separate scoring function that returns low-level details about matching character indices. And since there's a hard limit on the number of matches that will be displayed, the cost is essentially constant for each `draw_screen` call.

**Comment by garybernhardt** [comment]
Ahh, yeah, that crossed my mind as well, but I thought it would be gross to maintain. Maybe I'll make an attempt.

**Comment by garybernhardt** [comment]
This is merged into master as of d874c99dd7f0f94225a95da06fc487b0fa5b9edc.
