### ISSUE TITLE
Combination of umlauts and tabs breaks selecta's UI

### ISSUE THREAD

**Issue by untitaker** [garybernhardt/selecta#75]
The following command:

    python -c '[print("ä\t" * 200) for i in range(20)]' | selecta

looks like this:

![2015-02-01-133529_488x237_scrot](https://cloud.githubusercontent.com/assets/837573/5992076/4aba33f2-aa17-11e4-9457-58902c747dfb.png)

When I start typing, the cursor is still somewhere inbetween the suggestions:

![2015-02-01-133550_349x171_scrot](https://cloud.githubusercontent.com/assets/837573/5992078/6f96e968-aa17-11e4-8961-85a56a755e67.png)

Functionality-wise selecta works fine. This seems to occur only when the available suggestions exceed the screen's height.

This also occurs under zsh :P

**Comment by untitaker** [comment]
Note that this issue only occurs on rather narrow terminal widths, somewhat smaller than 80 chars or so.

**Comment by untitaker** [comment]
I've found a very simple algorithm for tab-expansion: http://stackoverflow.com/a/8900610

This would fix this issue and #73. I tested it, and it seems to output the same things as the ``expand`` command, apart from that it doesn't seem to deal with umlauts correctly, so it's sometimes off by one character.

**Comment by garybernhardt** [comment]
Fixed with the code you linked to. Tabs are the worst.

**Comment by untitaker** [comment]
On further thought, there are probably other graphemes whose column width differs from their amount of bytes in utf8.

**Comment by garybernhardt** [comment]
Selecta operates on graphemes (Ruby "chars"), so it does do the right thing. This example with Unicode snowmen should work just fine, for example:

```
python3 -c '[print("☃foo" * 200) for i in range(30)]' | selecta
```

**Comment by rschmitt** [comment]
Actually, @untitaker is right. Selecta does not place the cursor in the correct location when CJK characters are included in the query:
![screen shot 2015-02-23 at 10 30 33 pm](https://cloud.githubusercontent.com/assets/3725049/6344316/b79ee1d4-bbab-11e4-9be6-a46333bf61a8.png)
By contrast, here is how Heatseeker renders the query:
![screen shot 2015-02-23 at 10 31 41 pm](https://cloud.githubusercontent.com/assets/3725049/6344318/c7e78ca8-bbab-11e4-9378-29e7914b61c3.png)
This was easy to get right in Heatseeker, because all I had to do was call [this function](http://doc.rust-lang.org/std/str/trait.StrExt.html#tymethod.width) from the Rust standard library. In the Ruby case, I'm not sure how you would fix this without taking a dependency on a gem.

**Comment by garybernhardt** [comment]
2a08d045af1abadd1cb1ebd8fdeabf7e5dbf30a7 should fix that. I took the easy way out: draw the query last, so the cursor naturally lands at the end of it. No need to compute the display length of the query. You could still construct a case where Selecta truncates strings in the candidate list more than it needs to, but that's very minor and I doubt that anyone will even notice.
