### ISSUE TITLE
Option to ignore whitespace in query string

### ISSUE THREAD

**Issue by muellerj** [garybernhardt/selecta#88]
Hi Gary,

I enjoy `selecta` very much and use it mainly for file navigation (in Vim as well as ZSH). For some reason, I prefer separating parts of my query strings by spaces. For example, if I want to match `./lib/labels/some_file.rb`, I would type `lib lab some`.

The spaces are currently (correctly) interpreted as parts of the filename. Subsequently, I have a quick-and-dirty hack in [line 428](https://github.com/garybernhardt/selecta/blob/master/selecta#L428) to suit my needs (my filenames try not to contain any whitespace):

```ruby
# [...]

def score(string, query_chars)
  query_chars -= [" "]                   # <= my hack
  first_char, *rest = query_chars
  
  # [...]
```

If there are other people interested, maybe this could be worth an option à la `selecta -W` to ignore whitespace in the TTY input? I'd be happy to draft a pull request in case you're interested.

**Comment by rschmitt** [comment]
I've wondered about this. It seems like it would make `^W` more useful.

**Comment by maxjacobson** [comment]
I've occasionally wanted this

**Comment by garybernhardt** [comment]
I've also occasionally wanted this. However, if I'm remembering correctly, this is the third proposal for what spaces should mean, all mutually incompatible. One even proposed that spaces should have special word-boundary semantics within the matching algorithm itself.

I don't want to add options unless there's a really compelling reason; I think that their cost is tremendously underestimated. As for deciding what spaces should mean: this proposal seems like the best use of them right now. However, I want to wait it out, continue to use Selecta, and see what frustrates me. I still expect the matching algorithm to change, and that makes me especially cautious here since giving spaces special matching semantics may make sense.

I'm closing this issue, but only because I don't want to take immediate action on it, not because I think that it's a bad idea or will never be implemented.
